
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futbol-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: futbol-nginx
    depends_on:
      - app
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:8.0
    container_name: futbol-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: futbol
      MYSQL_USER: futbol
      MYSQL_PASSWORD: futbol
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: futbol-redis
    ports:
      - "6381:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: futbol-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db-data:

